version: "2"

run:
  relative-path-mode: gomod
  tests: false
  timeout: 2m
  concurrency: 5
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
    - typecheck
    - gosimple
    - bodyclose
    - unparam
