version: "2"

run:
  relative-path-mode: gomod
  tests: false
  timeout: 2m
  concurrency: 5
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - bodyclose
    - unparam
    - misspell
    - dupl
    - gocyclo
    - prealloc

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
