swagger: "2.0"
info:
  title: Semantic Search UI API
  description: API for semantic document search
  version: 0.0.0
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths: {}
