name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  UI_API_SERVICE_PATH: services/ui-api

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.UI_API_SERVICE_PATH }}/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2
          working-directory: ${{ env.UI_API_SERVICE_PATH }}